import { z } from 'zod/v4'

import { receivedInvoiceTb } from 'faktorio-db/schema'
import { protectedProc } from '../isAuthorizedMiddleware'
import { trpcContext } from '../trpcContext'
import { eq, desc, and, gte, lt, SQL } from 'drizzle-orm'
import { createInsertSchema } from 'drizzle-zod'
import { TRPCError } from '@trpc/server'
import { createOpenRouter } from '@openrouter/ai-sdk-provider'
import {
  APICallError,
  generateText,
  JSONParseError,
  NoObjectGeneratedError,
  Output
} from 'ai'
import { stringDateSchema, paymentMethodEnum } from './zodSchemas'

// Define Zod schema based on Drizzle schema, making fields optional/required as needed for creation
const receivedInvoiceCreateSchema = createInsertSchema(receivedInvoiceTb)
  .omit({
    id: true, // ID is generated by DB
    user_id: true, // Will be injected from context
    created_at: true, // Defaulted by DB
    updated_at: true, // Set on update
    supplier_contact_id: true // Handle contact linking separately if needed
  })
  .extend({
    status: z
      .enum(['received', 'verified', 'disputed', 'paid'])
      .default('received'),
    tags: z.array(z.string()).optional().default([]),
    items: z
      .array(
        z.object({
          description: z.string().optional(),
          quantity: z.number().optional(),
          unit_price: z.number().optional(),
          unit: z.string().optional(),
          vat_rate: z.number().optional(),
          total_without_vat: z.number().optional(),
          total_with_vat: z.number().optional(),
          accounting_code: z.string().optional()
        })
      )
      .optional()
      .default([]),
    // Make non-null fields explicitly required if not defaulted
    supplier_name: z.string().min(1),
    invoice_number: z.string().min(1),
    issue_date: stringDateSchema,
    due_date: stringDateSchema,
    total_with_vat: z.number(),
    currency: z.string().max(3).min(3).default('CZK'),
    payment_method: paymentMethodEnum.optional(),
    // Add fields not directly in DB schema but needed for UI/logic
    supplier_contact_id: z.string().optional(), // Reference to existing contact
    attachment_data: z.string().optional().nullable() // Base64 encoded image data
  })

// Meta strict outputs require every property, including line-item fields.
// Unknown values are represented by null instead of omitted properties.
const ocrResponseSchema = z.object({
  supplier_name: z.string().nullable(),
  supplier_street: z.string().nullable(),
  supplier_street2: z.string().nullable(),
  supplier_city: z.string().nullable(),
  supplier_zip: z.string().nullable(),
  supplier_country: z.string().nullable(),
  supplier_registration_no: z.string().nullable(),
  supplier_vat_no: z.string().nullable(),
  supplier_email: z.string().nullable(),
  supplier_phone: z.string().nullable(),
  invoice_number: z.string().nullable(),
  internal_number: z.string().nullable(),
  variable_symbol: z.string().nullable(),
  expense_category: z.string().nullable(),
  issue_date: stringDateSchema,
  taxable_supply_date: stringDateSchema.nullable(),
  due_date: stringDateSchema,
  receipt_date: stringDateSchema.nullable(),
  payment_date: stringDateSchema.nullable(),
  total_without_vat: z.number().nullable(),
  total_with_vat: z.number().nullable(),
  currency: z.string().nullable().describe('ISO 4217 currency code'),
  exchange_rate: z.number().nullable(),
  vat_base_21: z.number().nullable(),
  vat_21: z.number().nullable(),
  vat_base_15: z.number().nullable(),
  vat_15: z.number().nullable(),
  vat_base_10: z.number().nullable(),
  vat_10: z.number().nullable(),
  vat_base_0: z.number().nullable(),
  reverse_charge: z.boolean().nullable(),
  vat_regime: z.string().nullable(),
  payment_method: z
    .enum(['bank', 'cash', 'card', 'cod', 'crypto', 'other'])
    .nullable(),
  bank_account: z.string().nullable(),
  iban: z.string().nullable(),
  swift_bic: z.string().nullable(),
  items: z
    .array(
      z.object({
        description: z.string().nullable(),
        quantity: z.number().nullable(),
        unit_price: z.number().nullable(),
        unit: z.string().nullable(),
        vat_rate: z.number().nullable(),
        total_without_vat: z.number().nullable(),
        total_with_vat: z.number().nullable(),
        accounting_code: z.string().nullable()
      })
    )
    .nullable(),
  status: z.enum(['received', 'verified', 'disputed', 'paid']).nullable(),
  line_items_summary: z.string().nullable()
})

const OCR_MODEL = 'meta/muse-spark-1.3-contributor'
const OCR_REQUEST_TIMEOUT_MS = 45_000
const OCR_MAX_OUTPUT_TOKENS = 8192
const OCR_OUTPUT_LIMIT_MESSAGE =
  'Invoice extraction reached the output token limit before completing. Try processing fewer pages at a time.'

const extractionPrompt = `Extract invoice data from this invoice document.
Return ONLY a JSON object.
Include every field. If you cannot extract a nullable field, use null.
For dates, use the format YYYY-MM-DD. Use issue_date for taxable_supply_date if not specified otherwise.
Keep line_items_summary to at most 90 characters.
If the document is a credit note (dobropis), make all taxable amounts, VAT amounts, and totals negative.
If text is partially unreadable, leave "?" for each unreadable character.`

export const receivedInvoicesRouter = trpcContext.router({
  list: protectedProc
    .input(
      z.object({
        from: stringDateSchema.optional().nullable(),
        to: stringDateSchema.optional().nullable()
      })
    )
    .query(async ({ ctx, input }) => {
      const conditions: SQL[] = [eq(receivedInvoiceTb.user_id, ctx.user.id)]

      if (input.from) {
        conditions.push(gte(receivedInvoiceTb.taxable_supply_date, input.from))
      }
      if (input.to) {
        conditions.push(lt(receivedInvoiceTb.taxable_supply_date, input.to))
      }

      const invoices = await ctx.db
        .select()
        .from(receivedInvoiceTb)
        .where(and(...conditions))
        .orderBy(desc(receivedInvoiceTb.taxable_supply_date))
      return invoices
    }),

  getById: protectedProc
    .input(z.object({ id: z.string() }))
    .query(async ({ ctx, input }) => {
      const invoice = await ctx.db
        .select()
        .from(receivedInvoiceTb)
        .where(
          and(
            eq(receivedInvoiceTb.id, input.id),
            eq(receivedInvoiceTb.user_id, ctx.user.id)
          )
        )
        .limit(1)

      if (!invoice.length) {
        throw new TRPCError({
          code: 'NOT_FOUND',
          message: 'Invoice not found'
        })
      }

      return invoice[0]
    }),

  create: protectedProc
    .input(receivedInvoiceCreateSchema)
    .mutation(async ({ ctx, input }) => {
      const { attachment_data: _attachment_data, ...invoiceData } = input

      // Basic check for duplicate invoice for the same supplier/number
      const existing = await ctx.db
        .select({ id: receivedInvoiceTb.id })
        .from(receivedInvoiceTb)
        .where(
          and(
            eq(receivedInvoiceTb.user_id, ctx.user.id),
            eq(receivedInvoiceTb.supplier_name, invoiceData.supplier_name),
            eq(receivedInvoiceTb.invoice_number, invoiceData.invoice_number)
          )
        )
        .limit(1)

      if (existing.length > 0) {
        throw new TRPCError({
          code: 'CONFLICT',
          message:
            'An invoice with this number from this supplier already exists.'
        })
      }

      // Save the invoice
      const [newInvoice] = await ctx.db
        .insert(receivedInvoiceTb)

        .values({
          ...invoiceData,
          user_id: ctx.user.id,
          items: invoiceData.items ?? [],
          tags: invoiceData.tags ?? []
        })
        .returning()

      return newInvoice
    }),

  update: protectedProc
    .input(
      receivedInvoiceCreateSchema.extend({
        id: z.string()
      })
    )
    .mutation(async ({ ctx, input }) => {
      const { id, attachment_data: _attachment_data, ...updateData } = input

      // Check if invoice exists and belongs to user
      const existing = await ctx.db
        .select({ id: receivedInvoiceTb.id })
        .from(receivedInvoiceTb)
        .where(
          and(
            eq(receivedInvoiceTb.id, id),
            eq(receivedInvoiceTb.user_id, ctx.user.id)
          )
        )
        .limit(1)

      if (!existing.length) {
        throw new TRPCError({
          code: 'NOT_FOUND',
          message: 'Invoice not found or you do not have permission to edit it.'
        })
      }

      // Update the invoice
      const [updatedInvoice] = await ctx.db
        .update(receivedInvoiceTb)
        .set({
          ...updateData,
          updated_at: new Date().toISOString()
        })
        .where(eq(receivedInvoiceTb.id, id))
        .returning()

      return updatedInvoice
    }),

  delete: protectedProc
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      // Check if invoice exists and belongs to user
      const existing = await ctx.db
        .select({ id: receivedInvoiceTb.id })
        .from(receivedInvoiceTb)
        .where(
          and(
            eq(receivedInvoiceTb.id, input.id),
            eq(receivedInvoiceTb.user_id, ctx.user.id)
          )
        )
        .limit(1)

      if (!existing.length) {
        throw new TRPCError({
          code: 'NOT_FOUND',
          message:
            'Invoice not found or you do not have permission to delete it.'
        })
      }

      // Delete the invoice
      await ctx.db
        .delete(receivedInvoiceTb)
        .where(eq(receivedInvoiceTb.id, input.id))

      return { success: true }
    }),

  // Extract structured invoice data from an image or PDF using OpenRouter.
  extractInvoiceData: protectedProc
    .input(
      z.object({
        mimeType: z.string(),
        imageData: z.string() // Base64 encoded document data
      })
    )
    .mutation(async ({ ctx, input }) => {
      try {
        if (!ctx.env.OPENROUTER_API_KEY) {
          throw new TRPCError({
            code: 'INTERNAL_SERVER_ERROR',
            message: 'OPENROUTER_API_KEY is not configured'
          })
        }

        const base64Data = input.imageData.replace(/^data:[^;]+;base64,/, '')
        const openrouter = createOpenRouter({
          apiKey: ctx.env.OPENROUTER_API_KEY
        })
        const result = await generateText({
          // Reasoning is mandatory for Muse Spark and shares the output budget.
          model: openrouter(OCR_MODEL, { reasoning: { effort: 'minimal' } }),
          output: Output.object({ schema: ocrResponseSchema }),
          system: `You are a data extraction assistant. Your main objective is to extract invoice data from a czech invoice document. Most likely the invoice is in CZK currency, but on the invoice it is often represented as Kč. The format we want for currency field is ISO 4217.`,
          messages: [
            {
              role: 'user',
              content: [
                { type: 'text', text: extractionPrompt },
                {
                  type: 'file',
                  data: base64Data,
                  mediaType: input.mimeType,
                  ...(input.mimeType === 'application/pdf'
                    ? { filename: 'invoice.pdf' }
                    : {})
                }
              ]
            }
          ],
          abortSignal: AbortSignal.timeout(OCR_REQUEST_TIMEOUT_MS),
          maxRetries: 0,
          maxOutputTokens: OCR_MAX_OUTPUT_TOKENS,
          temperature: 0.2
        })

        if (result.finishReason === 'length' || !result.text.trim()) {
          console.error('Incomplete OCR response:', {
            responseId: result.response.id,
            finishReason: result.finishReason,
            usage: result.usage
          })
          throw new TRPCError({
            code: 'INTERNAL_SERVER_ERROR',
            message:
              result.finishReason === 'length'
                ? OCR_OUTPUT_LIMIT_MESSAGE
                : 'The invoice model returned no extraction data. Please try again.'
          })
        }

        const output = result.output
        return { ...output, currency: output.currency ?? 'CZK' }
      } catch (error) {
        console.error('OCR processing error:', error)
        if (error instanceof TRPCError) {
          throw error
        }
        if (APICallError.isInstance(error) && error.statusCode === 401) {
          throw new TRPCError({
            code: 'INTERNAL_SERVER_ERROR',
            message:
              'OpenRouter API key is invalid in backend configuration. Update OPENROUTER_API_KEY.'
          })
        }
        if (NoObjectGeneratedError.isInstance(error)) {
          throw new TRPCError({
            code: 'INTERNAL_SERVER_ERROR',
            message:
              error.finishReason === 'length'
                ? OCR_OUTPUT_LIMIT_MESSAGE
                : !error.text?.trim()
                  ? 'The invoice model returned no extraction data. Please try again.'
                  : JSONParseError.isInstance(error.cause)
                    ? 'Failed to parse OCR results'
                    : 'OCR results did not match expected format'
          })
        }
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: 'Failed to process image: ' + (error as Error).message
        })
      }
    })
})

export type ReceivedInvoicesRouter = typeof receivedInvoicesRouter
